using System;
using AlgoDDD.SharedKernel.Domain.BaseClasses;
using AlgoDDD.Strategy.Domain.ValueObjects;
using AlgoDDD.MarketData.Domain.ValueObjects;

namespace AlgoDDD.Strategy.Domain.Entities
{
    /// <summary>
    /// Represents a trading signal generated by a strategy.
    /// </summary>
    public class Signal : Entity<string>
    {
        public StockSymbol Symbol { get; private set; }
        public SignalType Type { get; private set; }
        public decimal Price { get; private set; }
        public string Reason { get; private set; }
        public DateTime GeneratedAt { get; private set; }
        public DateTime? ExecutedAt { get; private set; }
        public decimal? ExecutionPrice { get; private set; }
        public bool IsExecuted { get; private set; }
        public decimal? Quantity { get; private set; }
        public decimal? ProfitLoss { get; private set; }

        // EF Core private constructor
        private Signal() : base(string.Empty)
        {
            Symbol = null!;
            Reason = null!;
        }

        // Constructor for creating a new signal
        public Signal(
            StockSymbol symbol,
            SignalType type,
            decimal price,
            string reason,
            DateTime generatedAt) : base(Guid.NewGuid().ToString())
        {
            Symbol = symbol ?? throw new ArgumentNullException(nameof(symbol));
            Type = type;
            Price = price;
            Reason = reason ?? throw new ArgumentNullException(nameof(reason));
            GeneratedAt = generatedAt;
            IsExecuted = false;
        }

        /// <summary>
        /// Executes the signal with given execution price and quantity.
        /// </summary>
        public void Execute(decimal executionPrice, decimal quantity)
        {
            ExecutionPrice = executionPrice;
            Quantity = quantity;
            ExecutedAt = DateTime.UtcNow;
            IsExecuted = true;

            if (Type == SignalType.Buy || Type == SignalType.StrongBuy)
            {
                ProfitLoss = (executionPrice - Price) * quantity;
            }
            else if (Type == SignalType.Sell || Type == SignalType.StrongSell)
            {
                ProfitLoss = (Price - executionPrice) * quantity;
            }
        }

        /// <summary>
        /// Closes the signal at a given closing price, updating profit/loss.
        /// </summary>
        public void Close(decimal closingPrice)
        {
            if (!IsExecuted || ExecutedAt == null)
                return;

            var quantity = Quantity ?? 0;
            if (Type == SignalType.Buy || Type == SignalType.StrongBuy)
            {
                ProfitLoss = (closingPrice - (ExecutionPrice ?? Price)) * quantity;
            }
            else if (Type == SignalType.Sell || Type == SignalType.StrongSell)
            {
                ProfitLoss = ((ExecutionPrice ?? Price) - closingPrice) * quantity;
            }
        }
    }
}
